using System.Drawing;using System.Drawing.Drawing2D;using System.Drawing.Text;using System.Globalization;
namespace LovingCool.Studio2.Core;
public sealed class SceneRenderer{
 public Bitmap Render(Scene scene,IReadOnlyDictionary<string,(float Value,string Unit)> values){var b=new Bitmap(scene.Width,scene.Height);using var g=Graphics.FromImage(b);g.SmoothingMode=SmoothingMode.AntiAlias;g.TextRenderingHint=TextRenderingHint.AntiAliasGridFit;g.Clear(Parse(scene.Background));foreach(var n in scene.Nodes.Where(n=>n.Visible).OrderBy(n=>n.Z))Draw(g,n,values);return b;}
 void Draw(Graphics g,Node n,IReadOnlyDictionary<string,(float Value,string Unit)> values){var fg=Parse(n.Foreground);var ac=Parse(n.Accent);var data=Resolve(n,values);string value=data is null?"--":Format(data.Value.Value,data.Value.Unit);string text=n.Text.Replace("{time}",DateTime.Now.ToString("HH:mm")).Replace("{date}",DateTime.Now.ToString("dd.MM.yyyy")).Replace("{value}",value);
 if(n.Kind==NodeKind.Ring||n.Kind==NodeKind.Gauge){float d=Math.Min(n.Width,n.Height),pct=data is null?0:Math.Clamp((data.Value.Value-n.Min)/Math.Max(1,n.Max-n.Min),0,1);var r=new RectangleF(n.X,n.Y,d,d);using var p0=new Pen(Color.FromArgb(45,255,255,255),12);using var p1=new Pen(ac,12){StartCap=LineCap.Round,EndCap=LineCap.Round};g.DrawArc(p0,r,-90,360);g.DrawArc(p1,r,-90,(n.Kind==NodeKind.Gauge?270:360)*pct);Center(g,value,n.X,n.Y+d*.34f,d,n.FontSize,fg);Center(g,n.Text,n.X,n.Y+d*.68f,d,15,fg);return;}
 if(n.Kind==NodeKind.Bar){float pct=data is null?0:Math.Clamp((data.Value.Value-n.Min)/Math.Max(1,n.Max-n.Min),0,1);using var b0=new SolidBrush(Color.FromArgb(45,255,255,255));using var b1=new SolidBrush(ac);g.FillRounded(n.X,n.Y,n.Width,n.Height,n.Height/2,b0);g.FillRounded(n.X,n.Y,n.Width*pct,n.Height,n.Height/2,b1);return;}
 using var f=new Font("Segoe UI",n.FontSize,FontStyle.Bold,GraphicsUnit.Pixel);using var br=new SolidBrush(fg);g.DrawString(text,f,br,n.X,n.Y);}
 static (float Value,string Unit)? Resolve(Node n,IReadOnlyDictionary<string,(float Value,string Unit)> v){if(string.IsNullOrWhiteSpace(n.SensorId))return null;if(v.TryGetValue(n.SensorId,out var exact))return exact;var words=n.SensorId.Split(' ',StringSplitOptions.RemoveEmptyEntries);var k=v.Keys.FirstOrDefault(x=>words.All(w=>x.Contains(w,StringComparison.OrdinalIgnoreCase))&&!x.Contains("Thread",StringComparison.OrdinalIgnoreCase));return k!=null?v[k]:null;}
 static string Format(float v,string unit)=>unit switch{"°C"=>$"{v:0}°C","%"=>$"{v:0}%","MHz"=>$"{v:0} MHz","W"=>$"{v:0.0} W","RPM"=>$"{v:0} RPM",_=>$"{v:0.0}{unit}"};
 static Color Parse(string s){try{return ColorTranslator.FromHtml(s.Length==9?"#"+s[3..]:s);}catch{return Color.White;}}
 static void Center(Graphics g,string s,float x,float y,float w,float size,Color c){using var f=new Font("Segoe UI",size,FontStyle.Bold,GraphicsUnit.Pixel);using var br=new SolidBrush(c);var z=g.MeasureString(s,f);g.DrawString(s,f,br,x+(w-z.Width)/2,y,br);}
}
static class GraphicsEx{public static void FillRounded(this Graphics g,float x,float y,float w,float h,float r,Brush b){if(w<=0||h<=0)return;using var p=new GraphicsPath();float d=Math.Min(r*2,Math.Min(w,h));p.AddArc(x,y,d,d,180,90);p.AddArc(x+w-d,y,d,d,270,90);p.AddArc(x+w-d,y+h-d,d,d,0,90);p.AddArc(x,y+h-d,d,d,90,90);p.CloseFigure();g.FillPath(b,p);}}