using System.Windows;using System.Windows.Controls;using System.Windows.Input;using System.Windows.Media;using LovingCool.Studio2.Core;
namespace LovingCool.Studio2.App;
public sealed class EditorCanvas:FrameworkElement{
 public EditorViewModel? Model{get;set;} Point start;Node? drag;bool resizing;Rect original;
 public EditorCanvas(){Focusable=true;MouseLeftButtonDown+=Down;MouseMove+=Move;MouseLeftButtonUp+=Up;}
 protected override void OnRender(DrawingContext dc){base.OnRender(dc);double z=Math.Min(ActualWidth/520,ActualHeight/520);double ox=(ActualWidth-480*z)/2;double oy=(ActualHeight-480*z)/2;dc.DrawRoundedRectangle(new SolidColorBrush(Color.FromRgb(5,10,19)),null,new Rect(ox-14,oy-14,480*z+28,480*z+28),8,8);dc.PushTransform(new TranslateTransform(ox,oy));dc.PushTransform(new ScaleTransform(z,z));dc.DrawRectangle(new SolidColorBrush(Color.FromRgb(8,18,41)),null,new Rect(0,0,480,480));if(Model!=null)foreach(var n in Model.Nodes.Where(n=>n.Visible).OrderBy(n=>n.Z))Draw(dc,n,n==Model.Selected);dc.Pop();dc.Pop();}
 void Draw(DrawingContext dc,Node n,bool sel){var fg=(Brush)new BrushConverter().ConvertFromString(n.Foreground)!;var ac=(Brush)new BrushConverter().ConvertFromString(n.Accent)!;if(n.Kind is NodeKind.Ring or NodeKind.Gauge){var r=new Rect(n.X,n.Y,n.Width,n.Height);dc.DrawEllipse(null,new Pen(new SolidColorBrush(Color.FromArgb(55,255,255,255)),10),r.Location+new Vector(r.Width/2,r.Height/2),r.Width/2,r.Height/2);dc.DrawEllipse(null,new Pen(ac,4),r.Location+new Vector(r.Width/2,r.Height/2),r.Width/2-8,r.Height/2-8);Text(dc,n.Text,n.X+20,n.Y+n.Height/2-18,n.FontSize,fg);}else Text(dc,n.Text.Replace("{time}",DateTime.Now.ToString("HH:mm")).Replace("{date}",DateTime.Now.ToString("dd.MM.yyyy")),n.X,n.Y,n.FontSize,fg);if(sel){dc.DrawRectangle(null,new Pen(new SolidColorBrush(Color.FromRgb(33,215,255)),1.5),new Rect(n.X,n.Y,n.Width,n.Height));foreach(var p in new[]{new Point(n.X,n.Y),new Point(n.X+n.Width,n.Y),new Point(n.X,n.Y+n.Height),new Point(n.X+n.Width,n.Y+n.Height)})dc.DrawRectangle(Brushes.White,null,new Rect(p.X-4,p.Y-4,8,8));}}
 void Text(DrawingContext dc,string s,double x,double y,double size,Brush b){var ft=new FormattedText(s,System.Globalization.CultureInfo.CurrentUICulture,FlowDirection.LeftToRight,new Typeface("Segoe UI"),size,b,VisualTreeHelper.GetDpi(this).PixelsPerDip);dc.DrawText(ft,new Point(x,y));}
 Point Logical(Point p){double z=Math.Min(ActualWidth/520,ActualHeight/520);double ox=(ActualWidth-480*z)/2;double oy=(ActualHeight-480*z)/2;return new((p.X-ox)/z,(p.Y-oy)/z);}
 void Down(object s,MouseButtonEventArgs e){Focus();if(Model==null)return;var p=Logical(e.GetPosition(this));var hit=Model.Nodes.Reverse().FirstOrDefault(n=>n.Visible&&!n.Locked&&new Rect(n.X,n.Y,n.Width,n.Height).Contains(p));Model.Selected=hit;if(hit!=null){Model.Snapshot();drag=hit;start=p;original=new(hit.X,hit.Y,hit.Width,hit.Height);resizing=Math.Abs(p.X-(hit.X+hit.Width))<14&&Math.Abs(p.Y-(hit.Y+hit.Height))<14;CaptureMouse();}InvalidateVisual();}
 void Move(object s,MouseEventArgs e){if(drag==null||e.LeftButton!=MouseButtonState.Pressed)return;var p=Logical(e.GetPosition(this));double dx=p.X-start.X;double dy=p.Y-start.Y;if(resizing){drag.Width=(float)Math.Clamp(original.Width+dx,24,480-drag.X);drag.Height=(float)Math.Clamp(original.Height+dy,24,480-drag.Y);}else{drag.X=(float)Math.Clamp(original.X+dx,0,480-drag.Width);drag.Y=(float)Math.Clamp(original.Y+dy,0,480-drag.Height);}InvalidateVisual();}
 void Up(object s,MouseButtonEventArgs e){drag=null;ReleaseMouseCapture();InvalidateVisual();}
}