using System.Windows;using System.Windows.Controls;using System.Windows.Input;using System.Windows.Threading;using LovingCool.Studio2.Core;using LovingCool.Studio2.Device;using LovingCool.Studio2.Sensors;
namespace LovingCool.Studio2.App;
public partial class MainWindow:Window{
 readonly EditorViewModel vm=new();readonly LovingCool6Pro device=new();readonly SceneRenderer renderer=new();readonly DispatcherTimer timer=new(){Interval=TimeSpan.FromMilliseconds(500)};
 public MainWindow(){InitializeComponent();Canvas.Model=vm;LayerList.ItemsSource=vm.Nodes;SensorPicker.ItemsSource=vm.Sensors;Canvas.MouseLeftButtonUp+=(_,_)=>LoadInspector();RotationBox.SelectedIndex=vm.Project.Device.Rotation switch{90=>0,0=>1,180=>2,_=>3};timer.Tick+=Tick;timer.Start();Closed+=(_,_)=>{vm.Save();device.Dispose();vm.Dispose();};}
 void Tick(object? s,EventArgs e){try{vm.RefreshSensors();Canvas.InvalidateVisual();if(device.Connected){using var b=renderer.Render(vm.Project.Scene,vm.Values());device.Send(b,vm.Project.Device.Rotation);}}catch{}}
 void Connect_Click(object s,RoutedEventArgs e){try{device.Connect();device.SetBrightness(vm.Project.Device.Brightness);DeviceStatus.Text=$"● LOVINGCOOL 6PRO\n  {device.Port} • {device.Width}×{device.Height} • FW {device.Firmware}";DeviceStatus.Foreground=new System.Windows.Media.SolidColorBrush(System.Windows.Media.Color.FromRgb(61,224,155));}catch(Exception ex){MessageBox.Show(ex.Message,"LOVINGCOOL Studio 2");}}
 void Save_Click(object s,RoutedEventArgs e)=>vm.Save();void Undo_Click(object s,RoutedEventArgs e){vm.Undo();Canvas.InvalidateVisual();}void Redo_Click(object s,RoutedEventArgs e){vm.Redo();Canvas.InvalidateVisual();}
 void AddText(object s,RoutedEventArgs e)=>Add(NodeKind.Text);void AddClock(object s,RoutedEventArgs e)=>Add(NodeKind.Clock);void AddRing(object s,RoutedEventArgs e)=>Add(NodeKind.Ring);void AddGauge(object s,RoutedEventArgs e)=>Add(NodeKind.Gauge);void AddBar(object s,RoutedEventArgs e)=>Add(NodeKind.Bar);void AddGraph(object s,RoutedEventArgs e)=>Add(NodeKind.Graph);void AddImage(object s,RoutedEventArgs e)=>Add(NodeKind.Image);void AddSensor(object s,RoutedEventArgs e)=>Add(NodeKind.SensorText);
 void Add(NodeKind k){vm.Add(k);Canvas.InvalidateVisual();LoadInspector();}
 void AddPickedSensor(object s,RoutedEventArgs e){if(SensorPicker.SelectedItem is not SensorValue sv)return;vm.Snapshot();var n=new Node{Kind=NodeKind.SensorText,Name=sv.Hardware+" "+sv.Name,Text=sv.Name+"  {value}",SensorId=$"{sv.Hardware} {sv.Type} {sv.Name}",X=55,Y=350,Width=360,Height=50,FontSize=25};vm.Project.Scene.Nodes.Add(n);vm.Nodes.Add(n);vm.Selected=n;Canvas.InvalidateVisual();LoadInspector();}
 void LoadInspector(){var n=vm.Selected;if(n==null)return;NameBox.Text=n.Name;TextBox.Text=n.Text;XBox.Text=n.X.ToString("0");YBox.Text=n.Y.ToString("0");WBox.Text=n.Width.ToString("0");HBox.Text=n.Height.ToString("0");LayerList.SelectedItem=n;}
 void Apply_Click(object s,RoutedEventArgs e){var n=vm.Selected;if(n==null)return;vm.Snapshot();n.Name=NameBox.Text;n.Text=TextBox.Text;if(float.TryParse(XBox.Text,out var x))n.X=Math.Clamp(x,0,480-n.Width);if(float.TryParse(YBox.Text,out var y))n.Y=Math.Clamp(y,0,480-n.Height);if(float.TryParse(WBox.Text,out var w))n.Width=Math.Clamp(w,24,480-n.X);if(float.TryParse(HBox.Text,out var h))n.Height=Math.Clamp(h,24,480-n.Y);LayerList.Items.Refresh();Canvas.InvalidateVisual();}
 void Delete_Click(object s,RoutedEventArgs e){vm.Delete();Canvas.InvalidateVisual();}void LayerChanged(object s,SelectionChangedEventArgs e){if(LayerList.SelectedItem is Node n){vm.Selected=n;LoadInspector();Canvas.InvalidateVisual();}}
 void RotationChanged(object s,SelectionChangedEventArgs e){if(!IsLoaded)return;vm.Project.Device.Rotation=RotationBox.SelectedIndex switch{0=>90,1=>0,2=>180,_=>270};}
 void OnKey(object s,KeyEventArgs e){if(Keyboard.Modifiers.HasFlag(ModifierKeys.Control)&&e.Key==Key.Z){vm.Undo();Canvas.InvalidateVisual();e.Handled=true;}else if(Keyboard.Modifiers.HasFlag(ModifierKeys.Control)&&e.Key==Key.Y){vm.Redo();Canvas.InvalidateVisual();e.Handled=true;}else if(e.Key==Key.Delete&&!(Keyboard.FocusedElement is TextBox)){vm.Delete();Canvas.InvalidateVisual();e.Handled=true;}}
}