<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>WinExe</OutputType><TargetFramework>net8.0-windows</TargetFramework><UseWPF>true</UseWPF><EnableWindowsTargeting>true</EnableWindowsTargeting><Nullable>enable</Nullable><ImplicitUsings>enable</ImplicitUsings><AssemblyName>LOVINGCOOL Studio 2</AssemblyName><SelfContained>true</SelfContained><RuntimeIdentifier>win-x64</RuntimeIdentifier><PublishSingleFile>true</PublishSingleFile><IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract></PropertyGroup><ItemGroup><ProjectReference Include="..\Studio2.Core\Studio2.Core.csproj"/><ProjectReference Include="..\Studio2.Device\Studio2.Device.csproj"/><ProjectReference Include="..\Studio2.Sensors\Studio2.Sensors.csproj"/><ProjectReference Include="..\Studio2.Media\Studio2.Media.csproj"/></ItemGroup></Project>