using System.Drawing;using System.Drawing.Imaging;using System.IO.Ports;using System.Text;using System.Text.Json;using Microsoft.Win32;
namespace LovingCool.Studio2.Device;
public sealed class LovingCool6Pro:ILcdDevice{
 SerialPort? port;CancellationTokenSource? cts;readonly object gate=new();public bool Connected=>port?.IsOpen==true;public string? Port=>port?.PortName;public int Width{get;private set;}=480;public int Height{get;private set;}=480;public string Firmware{get;private set;}="?";
 static byte[] Control(byte key,byte[]? payload=null){payload??=[];ushort len=(ushort)(payload.Length+7);var b=new List<byte>{0x55,0xAA,(byte)len,(byte)(len>>8),key};b.AddRange(payload);ushort sum=(ushort)(b.Sum(x=>(int)x)&0xffff);b.Add((byte)sum);b.Add((byte)(sum>>8));return b.ToArray();}
 static string? Find(){try{using var root=Registry.LocalMachine.OpenSubKey(@"SYSTEM\CurrentControlSet\Enum\USB\VID_33C3&PID_7791");if(root!=null)foreach(var id in root.GetSubKeyNames()){using var k=root.OpenSubKey(id+@"\Device Parameters");if(k?.GetValue("PortName") is string p&&!string.IsNullOrWhiteSpace(p))return p;}}catch{}return null;}
 public void Connect(){Dispose();var p=Find()??throw new InvalidOperationException("LOVINGCOOL 6PRO (33C3:7791) не найден.");port=new SerialPort(p,LovingCoolIds.Baud){ReadTimeout=700,WriteTimeout=3000,DtrEnable=true};port.Open();lock(gate)port.Write([0xFF,0xD9,0xFF,0xD9,0,0,0,0],0,8);Thread.Sleep(120);Info();cts=new();_=Task.Run(()=>Heartbeat(cts.Token));}
 byte[] Cmd(byte key,byte[]? payload=null,bool read=true){if(!Connected)return[];var f=Control(key,payload);lock(gate){port!.DiscardInBuffer();port.Write(f,0,f.Length);if(!read)return[];var sw=System.Diagnostics.Stopwatch.StartNew();var b=new List<byte>();while(sw.ElapsedMilliseconds<900){while(port.BytesToRead>0)b.Add((byte)port.ReadByte());if(b.Count>=7&&b[0]==0x55&&b[1]==0xAA){int n=b[2]|b[3]<<8;if(b.Count>=n)return b.Take(n).ToArray();}Thread.Sleep(5);}return b.ToArray();}}
 void Info(){try{var r=Cmd(0x06);if(r.Length>7){using var d=JsonDocument.Parse(Encoding.UTF8.GetString(r,5,r.Length-7));var x=d.RootElement.TryGetProperty("data",out var data)?data:d.RootElement;if(x.TryGetProperty("width",out var w))Width=w.GetInt32();if(x.TryGetProperty("height",out var h))Height=h.GetInt32();if(x.TryGetProperty("version",out var v))Firmware=v.ToString();}}catch{}}
 async Task Heartbeat(CancellationToken t){while(!t.IsCancellationRequested&&Connected){try{Cmd(0x11,null,false);}catch{}try{await Task.Delay(1500,t);}catch{}}}
 public void SetBrightness(int v)=>Cmd(0x03,[(byte)Math.Clamp(v,0,100)],false);
 public void Send(Bitmap uprightFrame,int physicalRotation){using var src=new Bitmap(uprightFrame);if(physicalRotation!=0)src.RotateFlip(physicalRotation switch{90=>RotateFlipType.Rotate270FlipNone,180=>RotateFlipType.Rotate180FlipNone,270=>RotateFlipType.Rotate90FlipNone,_=>RotateFlipType.RotateNoneFlipNone});using var fitted=new Bitmap(Width,Height,PixelFormat.Format24bppRgb);using(var g=Graphics.FromImage(fitted))g.DrawImage(src,0,0,Width,Height);byte[] jpg=[];foreach(long q in new[]{88,80,72,64,56,48,40,32}){using var ms=new MemoryStream();var codec=ImageCodecInfo.GetImageEncoders().First(x=>x.FormatID==ImageFormat.Jpeg.Guid);using var ep=new EncoderParameters(1);ep.Param[0]=new EncoderParameter(System.Drawing.Imaging.Encoder.Quality,q);fitted.Save(ms,codec,ep);jpg=ms.ToArray();if(jpg.Length<=32768)break;}bool modern=!double.TryParse(Firmware.Replace(',','.'),System.Globalization.NumberStyles.Any,System.Globalization.CultureInfo.InvariantCulture,out var ver)||ver>=2.8;using var packet=new MemoryStream();if(modern)packet.Write(BitConverter.GetBytes(jpg.Length));packet.Write(jpg);if(modern){ushort sum=(ushort)(jpg.Sum(x=>(int)x)&0xffff);packet.Write(BitConverter.GetBytes(sum));}var bytes=packet.ToArray();lock(gate){port!.Write(bytes,0,bytes.Length);port.BaseStream.Flush();}}
 public void Dispose(){try{cts?.Cancel();}catch{}try{port?.Close();port?.Dispose();}catch{}port=null;}
}