using System.Drawing.Drawing2D;
using Microsoft.Win32;
namespace LovingCoolStudio;
public sealed class MainForm:Form {
 readonly PanelDevice panel=new(); readonly SensorService sensors=new(); readonly System.Windows.Forms.Timer renderTimer=new(){Interval=250}; readonly NotifyIcon tray=new();
 readonly Panel preview=new(){Width=520,Height=520,BackColor=Color.FromArgb(9,12,18)}; readonly Label status=new(){AutoSize=true,ForeColor=Color.FromArgb(142,156,180)}; readonly FlowLayoutPanel sensorList=new(){Dock=DockStyle.Fill,FlowDirection=FlowDirection.TopDown,WrapContents=false,AutoScroll=true};
 readonly List<Widget> widgets=[]; Dictionary<string,float> snapshot=[]; Bitmap? background; int rotation=90,brightness=80; bool mirror=false;
 readonly Color surface=Color.FromArgb(20,26,38), surface2=Color.FromArgb(28,36,51), accent=Color.FromArgb(83,133,255), text=Color.FromArgb(235,240,249), muted=Color.FromArgb(142,156,180);
 public MainForm(){Text="LOVINGCOOL Studio";Width=1380;Height=860;MinimumSize=new(1120,720);BackColor=Color.FromArgb(11,15,22);ForeColor=text;Font=new Font("Segoe UI",10);DoubleBuffered=true;Build();LoadDefaults();renderTimer.Tick+=(s,e)=>TickRender();renderTimer.Start();FormClosing+=Closing;Resize+=(s,e)=>{if(WindowState==FormWindowState.Minimized)HideToTray();};SetupTray();}
 Button Btn(string t,EventHandler onClick,bool primary=false){var b=new Button{Text=t,Height=42,Width=250,FlatStyle=FlatStyle.Flat,BackColor=primary?accent:surface2,ForeColor=Color.White,Cursor=Cursors.Hand,Margin=new Padding(0,4,0,4)};b.FlatAppearance.BorderSize=0;b.Click+=onClick;return b;}
 Label H(string t,int size=11,bool bold=false)=>new(){Text=t,AutoSize=true,ForeColor=bold?text:muted,Font=new Font("Segoe UI",size,bold?FontStyle.Bold:FontStyle.Regular),Margin=new Padding(0,10,0,5)};
 void Build(){
  var nav=new Panel{Dock=DockStyle.Left,Width=300,BackColor=Color.FromArgb(15,20,29),Padding=new Padding(24)};Controls.Add(nav);
  var logo=new Label{Text="LOVINGCOOL\nSTUDIO",AutoSize=true,ForeColor=Color.White,Font=new Font("Segoe UI",21,FontStyle.Bold),Location=new Point(24,24)};nav.Controls.Add(logo);
  status.Text="●  Дисплей не подключён";status.Location=new Point(24,92);nav.Controls.Add(status);
  var actions=new FlowLayoutPanel{Location=new Point(24,132),Width=252,Height=650,FlowDirection=FlowDirection.TopDown,WrapContents=false,AutoScroll=true};nav.Controls.Add(actions);
  actions.Controls.Add(Btn("Подключить LOVINGCOOL",(s,e)=>Connect(),true)); actions.Controls.Add(H("РЕЖИМ",9,true));
  actions.Controls.Add(Btn("Панель мониторинга",(s,e)=>{mirror=false;})); actions.Controls.Add(Btn("Зеркало монитора",(s,e)=>{mirror=true;}));
  actions.Controls.Add(H("СЦЕНА",9,true)); actions.Controls.Add(Btn("+ Текст",(s,e)=>AddText())); actions.Controls.Add(Btn("+ Часы",(s,e)=>AddClock())); actions.Controls.Add(Btn("Фоновое изображение…",(s,e)=>ChooseBackground())); actions.Controls.Add(Btn("Очистить сцену",(s,e)=>{widgets.Clear();preview.Invalidate();}));
  actions.Controls.Add(H("ОРИЕНТАЦИЯ",9,true));
  var rot=new ComboBox{Width=250,Height=38,DropDownStyle=ComboBoxStyle.DropDownList,BackColor=surface2,ForeColor=text};rot.Items.AddRange(["90° влево (для вашей СЖО)","0°","180°","90° вправо"]);rot.SelectedIndex=0;rot.SelectedIndexChanged+=(s,e)=>rotation=rot.SelectedIndex switch{0=>90,1=>0,2=>180,_=>270};actions.Controls.Add(rot);
  actions.Controls.Add(H("ЯРКОСТЬ",9,true));var br=new TrackBar{Width=250,Minimum=5,Maximum=100,Value=80,TickStyle=TickStyle.None};br.ValueChanged+=(s,e)=>{brightness=br.Value;if(panel.Connected)panel.SetBrightness(brightness);};actions.Controls.Add(br);
  actions.Controls.Add(Btn("Свернуть в трей",(s,e)=>HideToTray())); actions.Controls.Add(Btn("Автозапуск Windows",(s,e)=>ToggleStartup()));

  var main=new Panel{Dock=DockStyle.Fill,Padding=new Padding(28)};Controls.Add(main);
  var title=new Label{Text="Дизайнер экрана",AutoSize=true,ForeColor=text,Font=new Font("Segoe UI",24,FontStyle.Bold),Location=new Point(30,24)};main.Controls.Add(title);
  var sub=new Label{Text="480 × 480  •  перетаскивайте виджеты мышью  •  данные обновляются в реальном времени",AutoSize=true,ForeColor=muted,Location=new Point(32,66)};main.Controls.Add(sub);
  var stage=new Panel{Location=new Point(28,104),Size=new Size(580,590),BackColor=surface,Padding=new Padding(28)};main.Controls.Add(stage);preview.Location=new Point(30,30);preview.Paint+=PreviewPaint;preview.MouseDown+=PreviewDown;preview.MouseMove+=PreviewMove;stage.Controls.Add(preview);
  var right=new Panel{Location=new Point(632,104),Size=new Size(420,590),Anchor=AnchorStyles.Top|AnchorStyles.Bottom|AnchorStyles.Left|AnchorStyles.Right,BackColor=surface,Padding=new Padding(22)};main.Controls.Add(right);
  var st=H("Датчики компьютера",16,true);st.Dock=DockStyle.Top;right.Controls.Add(st);var hint=new Label{Text="LibreHardwareMonitor встроен. Выберите любой доступный датчик: температура, загрузка, частоты, мощность, вентиляторы, накопители, сеть и другое.",ForeColor=muted,Dock=DockStyle.Top,Height=70};right.Controls.Add(hint);sensorList.Padding=new Padding(0,8,0,0);right.Controls.Add(sensorList);sensorList.BringToFront();RefreshSensors();
 }
 void LoadDefaults(){widgets.Add(new Widget{Kind="clock",Label="{time}",X=34,Y=30,Size=52});widgets.Add(new Widget{Kind="sensor",SensorHint="CPU",Label="CPU  {value}",X=34,Y=120,Size=30});widgets.Add(new Widget{Kind="sensor",SensorHint="GPU",Label="GPU  {value}",X=34,Y=175,Size=30});widgets.Add(new Widget{Kind="sensor",SensorHint="Memory",Label="RAM  {value}",X=34,Y=230,Size=28});}
 void RefreshSensors(){snapshot=sensors.Snapshot();sensorList.Controls.Clear();foreach(var kv in snapshot.OrderBy(x=>x.Key).Take(300)){var b=Btn(kv.Key+"   "+Format(kv.Key,kv.Value),(s,e)=>{var key=((Button)s!).Tag!.ToString()!;widgets.Add(new Widget{Kind="sensor",SensorKey=key,Label=ShortName(key)+"  {value}",X=34,Y=320,Size=24});},false);b.Width=360;b.Height=48;b.TextAlign=ContentAlignment.MiddleLeft;b.Tag=kv.Key;sensorList.Controls.Add(b);}}
 void Connect(){try{panel.Connect();panel.SetBrightness(brightness);status.Text=$"●  {panel.PortName}  •  {panel.Width}×{panel.Height}  •  FW {panel.Firmware}";status.ForeColor=Color.FromArgb(80,210,150);}catch(Exception ex){MessageBox.Show(ex.Message,"LOVINGCOOL Studio",MessageBoxButtons.OK,MessageBoxIcon.Warning);}}
 Bitmap Compose(){Bitmap b;if(mirror){var screen=Screen.PrimaryScreen!.Bounds;b=new Bitmap(screen.Width,screen.Height);using var g=Graphics.FromImage(b);g.CopyFromScreen(screen.Location,Point.Empty,screen.Size);var fit=FitSquare(b);b.Dispose();b=fit;}else{b=background!=null?new Bitmap(background):new Bitmap(480,480);using var g=Graphics.FromImage(b);if(background==null){using var bg=new LinearGradientBrush(new Rectangle(0,0,480,480),Color.FromArgb(9,13,23),Color.FromArgb(24,34,57),45);g.FillRectangle(bg,0,0,480,480);}g.SmoothingMode=SmoothingMode.AntiAlias;g.TextRenderingHint=System.Drawing.Text.TextRenderingHint.AntiAliasGridFit;foreach(var w in widgets)DrawWidget(g,w);}return Rotate(b);}
 void DrawWidget(Graphics g,Widget w){string s=w.Label;if(w.Kind=="clock")s=s.Replace("{time}",DateTime.Now.ToString("HH:mm"));if(w.Kind=="sensor"){var key=w.SensorKey;if(string.IsNullOrEmpty(key))key=snapshot.Keys.FirstOrDefault(x=>x.Contains(w.SensorHint,StringComparison.OrdinalIgnoreCase));var val=key!=null&&snapshot.TryGetValue(key,out var v)?Format(key,v):"--";s=s.Replace("{value}",val);}using var f=new Font("Segoe UI",w.Size,FontStyle.Bold,GraphicsUnit.Pixel);using var shadow=new SolidBrush(Color.FromArgb(100,0,0,0));using var fg=new SolidBrush(Color.White);g.DrawString(s,f,shadow,w.X+2,w.Y+2);g.DrawString(s,f,fg,w.X,w.Y);}
 Bitmap Rotate(Bitmap src){if(rotation==0)return src;src.RotateFlip(rotation switch{90=>RotateFlipType.Rotate270FlipNone,180=>RotateFlipType.Rotate180FlipNone,270=>RotateFlipType.Rotate90FlipNone,_=>RotateFlipType.RotateNoneFlipNone});return src;}
 static Bitmap FitSquare(Bitmap src){var dst=new Bitmap(480,480);using var g=Graphics.FromImage(dst);g.InterpolationMode=InterpolationMode.HighQualityBicubic;float scale=Math.Max(480f/src.Width,480f/src.Height);int w=(int)(src.Width*scale),h=(int)(src.Height*scale);g.DrawImage(src,(480-w)/2,(480-h)/2,w,h);return dst;}
 void TickRender(){try{snapshot=sensors.Snapshot();preview.Invalidate();if(panel.Connected){using var b=Compose();panel.Send(b);}}catch{} }
 void PreviewPaint(object? s,PaintEventArgs e){using var b=Compose();e.Graphics.InterpolationMode=InterpolationMode.HighQualityBicubic;e.Graphics.DrawImage(b,new Rectangle(20,20,480,480));}
 Widget? drag;Point dragOffset;void PreviewDown(object? s,MouseEventArgs e){int x=e.X-20,y=e.Y-20;drag=widgets.OrderByDescending(w=>widgets.IndexOf(w)).FirstOrDefault(w=>x>=w.X&&x<=w.X+260&&y>=w.Y&&y<=w.Y+w.Size+16);if(drag!=null)dragOffset=new Point(x-drag.X,y-drag.Y);}
 void PreviewMove(object? s,MouseEventArgs e){if(e.Button==MouseButtons.Left&&drag!=null){drag.X=Math.Clamp(e.X-20-dragOffset.X,0,450);drag.Y=Math.Clamp(e.Y-20-dragOffset.Y,0,450);preview.Invalidate();}}
 void AddText(){widgets.Add(new Widget{Kind="text",Label="LOVINGCOOL",X=40,Y=350,Size=32});}void AddClock(){widgets.Add(new Widget{Kind="clock",Label="{time}",X=40,Y=350,Size=42});}
 void ChooseBackground(){using var d=new OpenFileDialog{Filter="Изображения|*.png;*.jpg;*.jpeg;*.bmp;*.webp"};if(d.ShowDialog()==DialogResult.OK){using var im=Image.FromFile(d.FileName);background=FitSquare(new Bitmap(im));}}
 string Format(string key,float v){if(key.Contains("Temperature"))return $"{v:0}°C";if(key.Contains("Load"))return $"{v:0}%";if(key.Contains("Clock"))return $"{v:0} MHz";if(key.Contains("Power"))return $"{v:0.0} W";if(key.Contains("Fan"))return $"{v:0} RPM";if(key.Contains("Data"))return $"{v:0.0} GB";return $"{v:0.0}";}static string ShortName(string k){var a=k.Split('•',StringSplitOptions.TrimEntries);return a.Length>2?a[^1]:k;}
 void SetupTray(){tray.Text="LOVINGCOOL Studio";tray.Icon=SystemIcons.Application;tray.Visible=true;var m=new ContextMenuStrip();m.Items.Add("Открыть",null,(s,e)=>{Show();WindowState=FormWindowState.Normal;Activate();});m.Items.Add("Выход",null,(s,e)=>{tray.Visible=false;Application.Exit();});tray.ContextMenuStrip=m;tray.DoubleClick+=(s,e)=>{Show();WindowState=FormWindowState.Normal;};}
 void HideToTray(){Hide();}void ToggleStartup(){try{using var k=Registry.CurrentUser.OpenSubKey(@"Software\Microsoft\Windows\CurrentVersion\Run",true)!;var n="LOVINGCOOL Studio";if(k.GetValue(n)==null){k.SetValue(n,$"\"{Application.ExecutablePath}\"");MessageBox.Show("Автозапуск включён.");}else{k.DeleteValue(n,false);MessageBox.Show("Автозапуск выключен.");}}catch(Exception ex){MessageBox.Show(ex.Message);}}
 void Closing(object? s,FormClosingEventArgs e){renderTimer.Stop();panel.Dispose();sensors.Dispose();tray.Visible=false;}
 sealed class Widget{public string Kind="text",Label="";public string? SensorKey,SensorHint;public int X,Y,Size=28;}
}