using System.Drawing.Drawing2D;
using Microsoft.Win32;
namespace LovingCoolStudio;
public sealed class MainForm:Form {
 readonly PanelDevice panel=new();readonly SensorService sensorService=new();readonly StudioProject project=ProjectStore.Load();readonly StudioCanvas canvas=new(){Dock=DockStyle.Fill};readonly System.Windows.Forms.Timer timer=new(){Interval=500};readonly NotifyIcon tray=new();
 readonly Color bg=Color.FromArgb(7,11,19),side=Color.FromArgb(10,16,27),surface=Color.FromArgb(14,22,37),surface2=Color.FromArgb(20,31,51),line=Color.FromArgb(39,53,79),fg=Color.FromArgb(240,245,255),muted=Color.FromArgb(135,152,181),accent=Color.FromArgb(78,83,244),cyan=Color.FromArgb(31,215,255);
 readonly FlowLayoutPanel layers=new(){FlowDirection=FlowDirection.TopDown,WrapContents=false,AutoScroll=true};readonly ComboBox sensorPicker=new(){DropDownStyle=ComboBoxStyle.DropDownList};readonly Label device=new();readonly TextBox txt=new();readonly NumericUpDown size=new(){Minimum=10,Maximum=110};readonly NumericUpDown xBox=new(){Minimum=0,Maximum=480},yBox=new(){Minimum=0,Maximum=480},wBox=new(){Minimum=10,Maximum=480},hBox=new(){Minimum=10,Maximum=480};Dictionary<string,float> sensors=[];bool mirror;
 public MainForm(){Text="LOVINGCOOL Studio";WindowState=FormWindowState.Maximized;StartPosition=FormStartPosition.CenterScreen;MinimumSize=new(1360,820);BackColor=bg;ForeColor=fg;Font=new("Segoe UI",10);try{Icon=Icon.ExtractAssociatedIcon(Application.ExecutablePath);}catch{}canvas.Project=project;canvas.SelectionChanged+=Select;Build();RefreshSensors();RefreshLayers();SetupTray();timer.Tick+=(_,_)=>Tick();timer.Start();FormClosing+=(_,_)=>{ProjectStore.Save(project);panel.Dispose();sensorService.Dispose();tray.Visible=false;};}
 Label L(string t,int s=10,bool b=false)=>new(){Text=t,AutoSize=true,ForeColor=b?fg:muted,Font=new("Segoe UI",s,b?FontStyle.Bold:FontStyle.Regular)};
 Button B(string t,EventHandler e,bool hot=false){var b=new Button{Text=t,Height=38,FlatStyle=FlatStyle.Flat,BackColor=hot?accent:surface2,ForeColor=fg,Font=new("Segoe UI",9.5f,FontStyle.Bold),Cursor=Cursors.Hand};b.FlatAppearance.BorderSize=hot?0:1;b.FlatAppearance.BorderColor=line;b.Click+=e;return b;}
 void Build(){var root=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=4,BackColor=bg};root.ColumnStyles.Add(new(SizeType.Absolute,220));root.ColumnStyles.Add(new(SizeType.Absolute,260));root.ColumnStyles.Add(new(SizeType.Percent,100));root.ColumnStyles.Add(new(SizeType.Absolute,340));Controls.Add(root);Side(root);Library(root);Workspace(root);Inspector(root);}
 void Side(TableLayoutPanel r){var p=new Panel{Dock=DockStyle.Fill,BackColor=side,Padding=new Padding(16)};r.Controls.Add(p,0,0);var logo=L("◈  LOVINGCOOL\n    STUDIO",16,true);logo.Dock=DockStyle.Top;logo.Height=70;p.Controls.Add(logo);var nav=new FlowLayoutPanel{Dock=DockStyle.Top,Height=390,FlowDirection=FlowDirection.TopDown,WrapContents=false,Padding=new Padding(0,12,0,0)};p.Controls.Add(nav);
 foreach(var z in new[]{("⌂  Главная",0),("▦  Редактор экрана",1),("◉  Мониторинг",2),("▶  Медиа",3),("▣  Зеркалирование",4),("◎  Профили",5),("⚙  Настройки",6)}){var b=B(z.Item1,(_,_)=>Nav(z.Item2),z.Item2==1);b.Width=188;b.TextAlign=ContentAlignment.MiddleLeft;nav.Controls.Add(b);}
 var foot=new FlowLayoutPanel{Dock=DockStyle.Bottom,Height=235,FlowDirection=FlowDirection.TopDown,WrapContents=false};p.Controls.Add(foot);device.Text="● LOVINGCOOL 6 PRO\n  отключено";device.ForeColor=muted;device.Width=188;device.Height=42;foot.Controls.Add(device);foot.Controls.Add(L("ЯРКОСТЬ",8,true));var br=new TrackBar{Width=188,Minimum=5,Maximum=100,Value=project.Brightness,TickStyle=TickStyle.None};br.ValueChanged+=(_,_)=>{project.Brightness=br.Value;if(panel.Connected)panel.SetBrightness(br.Value);};foot.Controls.Add(br);var c=B("Подключить",(_,_)=>Connect(),true);c.Width=188;foot.Controls.Add(c);var tr=B("Свернуть в трей",(_,_)=>Hide());tr.Width=188;foot.Controls.Add(tr);}
 void Library(TableLayoutPanel r){var p=new Panel{Dock=DockStyle.Fill,BackColor=surface,Padding=new Padding(12)};r.Controls.Add(p,1,0);var title=L("Элементы",14,true);title.Dock=DockStyle.Top;title.Height=38;p.Controls.Add(title);var tabs=new TabControl{Dock=DockStyle.Fill};p.Controls.Add(tabs);var all=new TabPage("Все"){BackColor=surface};var sens=new TabPage("Датчики"){BackColor=surface};tabs.TabPages.Add(all);tabs.TabPages.Add(sens);var grid=new FlowLayoutPanel{Dock=DockStyle.Fill,WrapContents=true,AutoScroll=true,Padding=new Padding(5)};all.Controls.Add(grid);
 foreach(var z in new[]{("T","Текст",WidgetType.Text),("◷","Часы",WidgetType.Clock),("◉","Кольцо",WidgetType.Ring),("▰","Шкала",WidgetType.Bar),("⌁","Датчик",WidgetType.Sensor),("▧","Изображение",WidgetType.Image)}){var type=z.Item3;var b=B(z.Item1+"\n"+z.Item2,(_,_)=>Add(type));b.Width=102;b.Height=64;b.Margin=new Padding(4);grid.Controls.Add(b);}
 var sf=new FlowLayoutPanel{Dock=DockStyle.Fill,FlowDirection=FlowDirection.TopDown,WrapContents=false,Padding=new Padding(6)};sens.Controls.Add(sf);sensorPicker.Width=220;sensorPicker.BackColor=surface2;sensorPicker.ForeColor=fg;sf.Controls.Add(sensorPicker);var ab=B("+ Добавить датчик",(_,_)=>AddSensor(),true);ab.Width=220;sf.Controls.Add(ab);sf.Controls.Add(L("CPU / GPU / RAM / VRAM\nтемпературы, загрузка, частоты,\nмощность и вентиляторы",8));}
 void Workspace(TableLayoutPanel r){var p=new Panel{Dock=DockStyle.Fill,BackColor=bg,Padding=new Padding(18)};r.Controls.Add(p,2,0);var top=new Panel{Dock=DockStyle.Top,Height=68};p.Controls.Add(top);var h=L("Редактор экрана",21,true);h.Location=new(0,0);top.Controls.Add(h);var sub=L("480 × 480 • логический холст всегда прямо • поворот только на устройстве",8);sub.Location=new(2,39);top.Controls.Add(sub);var save=B("Сохранить",(_,_)=>{ProjectStore.Save(project);},true);save.Width=100;save.Location=new(430,5);top.Controls.Add(save);var undo=B("Сетка",(_,_)=>canvas.Invalidate());undo.Width=80;undo.Location=new(540,5);top.Controls.Add(undo);
 var presets=new FlowLayoutPanel{Dock=DockStyle.Bottom,Height=118,BackColor=surface,Padding=new Padding(8),WrapContents=false};p.Controls.Add(presets);foreach(var n in new[]{"NEON","SYSTEM","MINIMAL","CLOCK","GAMING"}){var b=B(n,(_,_)=>Preset(n));b.Width=105;b.Height=82;b.Margin=new Padding(5);presets.Controls.Add(b);}
 var frame=new Panel{Dock=DockStyle.Fill,BackColor=surface,Padding=new Padding(22)};p.Controls.Add(frame);frame.BringToFront();frame.Controls.Add(canvas);}
 void Inspector(TableLayoutPanel r){var p=new Panel{Dock=DockStyle.Fill,BackColor=side,Padding=new Padding(12)};r.Controls.Add(p,3,0);var tabs=new TabControl{Dock=DockStyle.Fill};p.Controls.Add(tabs);var pr=new TabPage("Свойства"){BackColor=side};var la=new TabPage("Слои"){BackColor=side};tabs.TabPages.Add(pr);tabs.TabPages.Add(la);var body=new FlowLayoutPanel{Dock=DockStyle.Fill,FlowDirection=FlowDirection.TopDown,WrapContents=false,AutoScroll=true,Padding=new Padding(8)};pr.Controls.Add(body);
 body.Controls.Add(L("ТЕКСТ / ПОДПИСЬ",8,true));txt.Width=285;body.Controls.Add(txt);body.Controls.Add(L("РАЗМЕР ШРИФТА",8,true));size.Width=285;body.Controls.Add(size);body.Controls.Add(L("ПОЗИЦИЯ И РАЗМЕР",8,true));foreach(var q in new[]{("X",xBox),("Y",yBox),("W",wBox),("H",hBox)}){var row=new FlowLayoutPanel{Width=285,Height=34};row.Controls.Add(L(q.Item1,9,true));q.Item2.Width=95;row.Controls.Add(q.Item2);body.Controls.Add(row);}var apply=B("Применить",(_,_)=>Apply(),true);apply.Width=285;body.Controls.Add(apply);var del=B("Удалить",(_,_)=>Delete());del.Width=285;body.Controls.Add(del);body.Controls.Add(L("ОРИЕНТАЦИЯ ФИЗИЧЕСКОГО LCD",8,true));var rot=new ComboBox{Width=285,DropDownStyle=ComboBoxStyle.DropDownList,BackColor=surface2,ForeColor=fg};rot.Items.AddRange(["90° влево","0°","180°","90° вправо"]);rot.SelectedIndex=project.Rotation switch{90=>0,0=>1,180=>2,_=>3};rot.SelectedIndexChanged+=(_,_)=>project.Rotation=rot.SelectedIndex switch{0=>90,1=>0,2=>180,_=>270};body.Controls.Add(rot);layers.Dock=DockStyle.Fill;la.Controls.Add(layers);}
 void Tick(){try{sensors=sensorService.Snapshot();canvas.Sensors=sensors;canvas.Invalidate();if(panel.Connected){using var logical=mirror?Capture():canvas.RenderLogical();using var output=Rotate(logical);panel.Send(output);}}catch{}}
 Bitmap Rotate(Bitmap src){var b=new Bitmap(src);if(project.Rotation!=0)b.RotateFlip(project.Rotation switch{90=>RotateFlipType.Rotate270FlipNone,180=>RotateFlipType.Rotate180FlipNone,270=>RotateFlipType.Rotate90FlipNone,_=>RotateFlipType.RotateNoneFlipNone});return b;}
 Bitmap Capture(){var s=Screen.PrimaryScreen!.Bounds;using var cap=new Bitmap(s.Width,s.Height);using(var g=Graphics.FromImage(cap))g.CopyFromScreen(s.Location,Point.Empty,s.Size);var d=new Bitmap(480,480);using(var g=Graphics.FromImage(d)){g.InterpolationMode=InterpolationMode.HighQualityBicubic;float z=Math.Max(480f/s.Width,480f/s.Height);g.DrawImage(cap,(480-s.Width*z)/2,(480-s.Height*z)/2,s.Width*z,s.Height*z);}return d;}
 void Connect(){try{panel.Connect();panel.SetBrightness(project.Brightness);device.Text=$"● LOVINGCOOL 6 PRO\n  {panel.PortName} • {panel.Width}×{panel.Height} • FW {panel.Firmware}";device.ForeColor=Color.FromArgb(65,230,155);}catch(Exception ex){MessageBox.Show(ex.Message,"LOVINGCOOL Studio");}}
 void RefreshSensors(){sensors=sensorService.Snapshot();sensorPicker.Items.Clear();foreach(var k in sensors.Keys.Where(k=>!k.Contains("Thread")&&!k.Contains("Core #")).OrderBy(k=>k).Take(100))sensorPicker.Items.Add(new Choice(k,Short(k)));if(sensorPicker.Items.Count>0)sensorPicker.SelectedIndex=0;}
 void Add(WidgetType type){var w=new StudioWidget{Type=type,Name=type.ToString(),X=55,Y=55,W=type==WidgetType.Ring?170:200,H=type==WidgetType.Ring?170:55,Text=type switch{WidgetType.Clock=>"{time}",WidgetType.Ring=>"CPU",_=>"LOVINGCOOL"},SensorHint=type==WidgetType.Ring?"CPU Temperature":null};project.Widgets.Add(w);RefreshLayers();Select(w);canvas.Invalidate();}
 void AddSensor(){if(sensorPicker.SelectedItem is not Choice c)return;var w=new StudioWidget{Type=WidgetType.Sensor,Name=c.Label,Text=c.Label+"  {value}",SensorKey=c.Key,X=50,Y=340,W=350,H=48,FontSize=25};project.Widgets.Add(w);RefreshLayers();Select(w);}
 void Select(StudioWidget? w){if(w==null)return;txt.Text=w.Text;size.Value=(decimal)Math.Clamp(w.FontSize,10,110);xBox.Value=(decimal)Math.Clamp(w.X,0,480);yBox.Value=(decimal)Math.Clamp(w.Y,0,480);wBox.Value=(decimal)Math.Clamp(w.W,10,480);hBox.Value=(decimal)Math.Clamp(w.H,10,480);}
 StudioWidget? Current=>project.Widgets.FirstOrDefault(w=>txt.Tag is Guid id&&w.Id==id)??canvas.Selected;
 void Apply(){var w=canvas.Selected;if(w==null)return;w.Text=txt.Text;w.FontSize=(float)size.Value;w.X=(float)xBox.Value;w.Y=(float)yBox.Value;w.W=(float)wBox.Value;w.H=(float)hBox.Value;RefreshLayers();canvas.Invalidate();}
 void Delete(){var w=canvas.Selected;if(w==null)return;project.Widgets.Remove(w);RefreshLayers();canvas.Invalidate();}
 void RefreshLayers(){layers.Controls.Clear();foreach(var w in project.Widgets.AsEnumerable().Reverse()){var b=B((w.Visible?"◉ ":"○ ")+w.Name,(_,_)=>Select(w));b.Width=285;b.Height=36;b.TextAlign=ContentAlignment.MiddleLeft;layers.Controls.Add(b);}}
 void Preset(string n){project.Widgets.Clear();if(n=="MINIMAL"){project.Widgets.Add(new(){Type=WidgetType.Clock,Name="Clock",Text="{time}",X=110,Y=150,W=260,H=90,FontSize=78});project.Widgets.Add(new(){Type=WidgetType.Sensor,Name="CPU",Text="CPU  {value}",SensorHint="CPU Load",X=170,Y=280,W=180,H=45,FontSize=26});}else if(n=="CLOCK"){project.Widgets.Add(new(){Type=WidgetType.Clock,Name="Clock",Text="{time}",X=100,Y=150,W=280,H=90,FontSize=82});project.Widgets.Add(new(){Type=WidgetType.Text,Name="Date",Text="{date}",X=155,Y=265,W=190,H=40,FontSize=22});}else{project.Widgets.AddRange(ProjectStore.New().Widgets);}RefreshLayers();canvas.Invalidate();}
 void Nav(int n){if(n==4)mirror=true;else{mirror=false;if(n==2)RefreshSensors();if(n==5){ProjectStore.Save(project);MessageBox.Show("Профиль сохранён.");}if(n==6)Startup();}}
 void Startup(){try{using var k=Registry.CurrentUser.OpenSubKey(@"Software\Microsoft\Windows\CurrentVersion\Run",true)!;const string n="LOVINGCOOL Studio";if(k.GetValue(n)==null){k.SetValue(n,$"\"{Application.ExecutablePath}\"");MessageBox.Show("Автозапуск включён.");}else{k.DeleteValue(n,false);MessageBox.Show("Автозапуск выключен.");}}catch{}}
 void SetupTray(){tray.Icon=Icon??SystemIcons.Application;tray.Text="LOVINGCOOL Studio";tray.Visible=true;var m=new ContextMenuStrip();m.Items.Add("Открыть",null,(_,_)=>{Show();WindowState=FormWindowState.Maximized;});m.Items.Add("Выход",null,(_,_)=>Application.Exit());tray.ContextMenuStrip=m;tray.DoubleClick+=(_,_)=>Show();}
 static string Short(string k){var a=k.Split('•',StringSplitOptions.TrimEntries);return a.Length>2?$"{a[0]} · {a[^1]}":k;} sealed record Choice(string Key,string Label){public override string ToString()=>Label;}
}