using System.Drawing.Drawing2D;
using System.Drawing.Text;
using System.Text.Json;
using Microsoft.Win32;

namespace LovingCoolStudio;

public sealed class MainForm : Form {
 readonly PanelDevice panel=new(); readonly SensorService sensors=new(); readonly System.Windows.Forms.Timer timer=new(){Interval=500}; readonly NotifyIcon tray=new();
 readonly Color bg=Color.FromArgb(8,12,20),side=Color.FromArgb(11,17,28),surface=Color.FromArgb(15,23,38),surface2=Color.FromArgb(21,31,50),line=Color.FromArgb(38,51,76),fg=Color.FromArgb(239,244,255),muted=Color.FromArgb(137,153,181),accent=Color.FromArgb(89,80,245),cyan=Color.FromArgb(38,211,255);
 readonly PreviewCanvas preview=new(){BackColor=Color.FromArgb(6,10,17)}; readonly Label device=new(); readonly ComboBox sensorPicker=new(){DropDownStyle=ComboBoxStyle.DropDownList};
 readonly FlowLayoutPanel layerList=new(){FlowDirection=FlowDirection.TopDown,WrapContents=false,AutoScroll=true}; readonly TextBox propText=new(); readonly NumericUpDown propSize=new(){Minimum=10,Maximum=110,Value=28};
 readonly List<Widget> widgets=[]; Dictionary<string,float> snap=[]; Bitmap? background; Widget? selected,drag; Point dragOffset; int rotation=90,brightness=80; bool mirror;
 public MainForm(){Text="LOVINGCOOL Studio";StartPosition=FormStartPosition.CenterScreen;WindowState=FormWindowState.Maximized;MinimumSize=new(1360,820);BackColor=bg;ForeColor=fg;Font=new("Segoe UI",10);DoubleBuffered=true;try{Icon=Icon.ExtractAssociatedIcon(Application.ExecutablePath);}catch{} Build();LoadScene();RefreshSensors();SetupTray();timer.Tick+=(_,_)=>Tick();timer.Start();FormClosing+=(_,_)=>{SaveScene();timer.Stop();panel.Dispose();sensors.Dispose();tray.Visible=false;};}
 Label LabelX(string s,int size=10,bool bold=false,Color? color=null)=>new(){Text=s,AutoSize=true,ForeColor=color??(bold?fg:muted),Font=new("Segoe UI",size,bold?FontStyle.Bold:FontStyle.Regular)};
 Button ButtonX(string s,EventHandler ev,bool hot=false){var b=new Button{Text=s,Height=38,FlatStyle=FlatStyle.Flat,BackColor=hot?accent:surface2,ForeColor=fg,Font=new("Segoe UI",9.5f,FontStyle.Bold),Cursor=Cursors.Hand};b.FlatAppearance.BorderSize=hot?0:1;b.FlatAppearance.BorderColor=line;b.Click+=ev;return b;}
 void Build(){var root=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=3,RowCount=1,BackColor=bg};root.ColumnStyles.Add(new(SizeType.Absolute,230));root.ColumnStyles.Add(new(SizeType.Percent,100));root.ColumnStyles.Add(new(SizeType.Absolute,360));Controls.Add(root);BuildSide(root);BuildWorkspace(root);BuildInspector(root);}
 void BuildSide(TableLayoutPanel root){var p=new Panel{Dock=DockStyle.Fill,BackColor=side,Padding=new Padding(18)};root.Controls.Add(p,0,0);
  var logo=LabelX("◈  LOVINGCOOL\n    STUDIO",17,true);logo.Dock=DockStyle.Top;logo.Height=72;p.Controls.Add(logo);
  var nav=new FlowLayoutPanel{Dock=DockStyle.Top,Height=370,FlowDirection=FlowDirection.TopDown,WrapContents=false,Padding=new Padding(0,14,0,0)};p.Controls.Add(nav);
  foreach(var item in new[]{("▦  Редактор",0),("◉  Мониторинг",1),("▣  Зеркалирование",2),("▧  Фон / медиа",3),("◎  Профили",4),("⚙  Настройки",5)}){var b=ButtonX(item.Item1,(_,_)=>Nav(item.Item2),item.Item2==0);b.Width=194;b.TextAlign=ContentAlignment.MiddleLeft;nav.Controls.Add(b);}
  var foot=new FlowLayoutPanel{Dock=DockStyle.Bottom,Height=245,FlowDirection=FlowDirection.TopDown,WrapContents=false};p.Controls.Add(foot);
  device.Text="●  LOVINGCOOL 6 PRO\n    отключено";device.ForeColor=muted;device.Width=194;device.Height=46;foot.Controls.Add(device);foot.Controls.Add(LabelX("ЯРКОСТЬ",8,true));
  var br=new TrackBar{Width=194,Minimum=5,Maximum=100,Value=80,TickStyle=TickStyle.None};br.ValueChanged+=(_,_)=>{brightness=br.Value;if(panel.Connected)panel.SetBrightness(brightness);};foot.Controls.Add(br);
  var con=ButtonX("Подключить дисплей",(_,_)=>Connect(),true);con.Width=194;foot.Controls.Add(con);var trayb=ButtonX("Свернуть в трей",(_,_)=>Hide());trayb.Width=194;foot.Controls.Add(trayb);
 }
 void BuildWorkspace(TableLayoutPanel root){var host=new Panel{Dock=DockStyle.Fill,BackColor=bg,Padding=new Padding(26,20,26,20)};root.Controls.Add(host,1,0);
  var head=new Panel{Dock=DockStyle.Top,Height=70};host.Controls.Add(head);var h=LabelX("Редактор экрана",22,true);h.Location=new(0,0);head.Controls.Add(h);var sub=LabelX("480 × 480  •  предпросмотр всегда прямо  •  поворот применяется только к физическому экрану",9);sub.Location=new(2,40);head.Controls.Add(sub);
  var bottom=new Panel{Dock=DockStyle.Bottom,Height=138,BackColor=surface,Padding=new Padding(12)};host.Controls.Add(bottom);var presets=new FlowLayoutPanel{Dock=DockStyle.Fill,WrapContents=false,AutoScroll=true};bottom.Controls.Add(presets);
  foreach(var n in new[]{"NEON","CYBER","MINIMAL","SYSTEM","GAMING","CLOCK"}){var b=ButtonX(n,(_,_)=>Preset(n));b.Width=112;b.Height=96;b.Margin=new Padding(5);presets.Controls.Add(b);}
  var stage=new Panel{Dock=DockStyle.Fill,BackColor=surface,Padding=new Padding(18)};host.Controls.Add(stage);stage.BringToFront();
  preview.Size=new(520,520);preview.Anchor=AnchorStyles.None;stage.Controls.Add(preview);stage.Resize+=(_,_)=>preview.Location=new((stage.ClientSize.Width-preview.Width)/2,(stage.ClientSize.Height-preview.Height)/2);
  preview.Paint+=PaintPreview;preview.MouseDown+=MouseDownPreview;preview.MouseMove+=MouseMovePreview;preview.MouseUp+=(_,_)=>drag=null;
 }
 void BuildInspector(TableLayoutPanel root){var p=new Panel{Dock=DockStyle.Fill,BackColor=side,Padding=new Padding(16)};root.Controls.Add(p,2,0);
  var tabs=new TabControl{Dock=DockStyle.Fill,Appearance=TabAppearance.Normal};p.Controls.Add(tabs);var add=new TabPage("Элементы"){BackColor=side,ForeColor=fg};var props=new TabPage("Свойства"){BackColor=side,ForeColor=fg};tabs.TabPages.Add(add);tabs.TabPages.Add(props);BuildAdd(add);BuildProps(props);
 }
 void BuildAdd(Control p){var grid=new FlowLayoutPanel{Dock=DockStyle.Top,Height=220,WrapContents=true,Padding=new Padding(8)};p.Controls.Add(grid);
  foreach(var a in new[]{("T","Текст","text"),("◷","Часы","clock"),("°C","Темп.","Temperature"),("%","Загрузка","Load"),("MHz","Частота","Clock"),("W","Мощность","Power"),("RPM","Вентил.","Fan"),("RAM","Память","Memory"),("NET","Сеть","Network"),("▧","Фон","background")}){var k=a.Item3;var b=ButtonX(a.Item1+"\n"+a.Item2,(_,_)=>Add(k));b.Width=92;b.Height=58;b.Margin=new Padding(4);grid.Controls.Add(b);}
  var sh=LabelX("ДАТЧИК",9,true);sh.Dock=DockStyle.Top;p.Controls.Add(sh);sensorPicker.Dock=DockStyle.Top;sensorPicker.Height=32;sensorPicker.BackColor=surface2;sensorPicker.ForeColor=fg;p.Controls.Add(sensorPicker);
  var add=ButtonX("+ Добавить выбранный",(_,_)=>AddSensor(),true);add.Dock=DockStyle.Top;p.Controls.Add(add);
  var hint=LabelX("Показываются полезные агрегированные датчики.\nПолный список остаётся в выпадающем меню.",8);hint.Dock=DockStyle.Top;hint.Height=45;p.Controls.Add(hint);
 }
 void BuildProps(Control p){var body=new FlowLayoutPanel{Dock=DockStyle.Fill,FlowDirection=FlowDirection.TopDown,WrapContents=false,AutoScroll=true,Padding=new Padding(10)};p.Controls.Add(body);
  body.Controls.Add(LabelX("ТЕКСТ / ШАБЛОН",8,true));propText.Width=300;propText.BackColor=surface2;propText.ForeColor=fg;body.Controls.Add(propText);body.Controls.Add(LabelX("РАЗМЕР",8,true));propSize.Width=300;body.Controls.Add(propSize);
  var apply=ButtonX("Применить",(_,_)=>Apply(),true);apply.Width=300;body.Controls.Add(apply);var del=ButtonX("Удалить элемент",(_,_)=>Delete());del.Width=300;body.Controls.Add(del);
  body.Controls.Add(LabelX("ОРИЕНТАЦИЯ ФИЗИЧЕСКОГО ЭКРАНА",8,true));var rot=new ComboBox{Width=300,DropDownStyle=ComboBoxStyle.DropDownList,BackColor=surface2,ForeColor=fg};rot.Items.AddRange(["90° влево","0°","180°","90° вправо"]);rot.SelectedIndex=0;rot.SelectedIndexChanged+=(_,_)=>rotation=rot.SelectedIndex switch{0=>90,1=>0,2=>180,_=>270};body.Controls.Add(rot);
  body.Controls.Add(LabelX("СЛОИ",8,true));layerList.Width=300;layerList.Height=300;body.Controls.Add(layerList);var bgbtn=ButtonX("Выбрать фон…",(_,_)=>ChooseBackground());bgbtn.Width=300;body.Controls.Add(bgbtn);
 }
 void Nav(int i){if(i==0){mirror=false;}else if(i==1){RefreshSensors();MessageBox.Show($"Найдено датчиков: {snap.Count}. Выберите нужный справа.","Мониторинг");}else if(i==2){mirror=true;}else if(i==3)ChooseBackground();else if(i==4)SaveScene();else ToggleStartup();}
 void Connect(){try{panel.Connect();panel.SetBrightness(brightness);device.Text=$"●  LOVINGCOOL 6 PRO\n    {panel.PortName} • {panel.Width}×{panel.Height} • FW {panel.Firmware}";device.ForeColor=Color.FromArgb(70,225,155);}catch(Exception ex){MessageBox.Show(ex.Message,"LOVINGCOOL Studio",MessageBoxButtons.OK,MessageBoxIcon.Warning);}}
 void Tick(){try{snap=sensors.Snapshot();preview.Invalidate();if(panel.Connected){using var logical=ComposeLogical();using var output=RotateForDevice(logical);panel.Send(output);}}catch{}}
 Bitmap ComposeLogical(){if(mirror){var r=Screen.PrimaryScreen!.Bounds;using var cap=new Bitmap(r.Width,r.Height);using(var g=Graphics.FromImage(cap))g.CopyFromScreen(r.Location,Point.Empty,r.Size);return Fit(cap);}var b=background!=null?new Bitmap(background):new Bitmap(480,480);using var g2=Graphics.FromImage(b);g2.SmoothingMode=SmoothingMode.AntiAlias;g2.TextRenderingHint=TextRenderingHint.AntiAliasGridFit;if(background==null){using var gr=new LinearGradientBrush(new Rectangle(0,0,480,480),Color.FromArgb(6,13,29),Color.FromArgb(25,8,48),35);g2.FillRectangle(gr,0,0,480,480);}foreach(var w in widgets)DrawWidget(g2,w);return b;}
 Bitmap RotateForDevice(Bitmap logical){var b=new Bitmap(logical);if(rotation!=0)b.RotateFlip(rotation switch{90=>RotateFlipType.Rotate270FlipNone,180=>RotateFlipType.Rotate180FlipNone,270=>RotateFlipType.Rotate90FlipNone,_=>RotateFlipType.RotateNoneFlipNone});return b;}
 void PaintPreview(object? s,PaintEventArgs e){using var b=ComposeLogical();e.Graphics.InterpolationMode=InterpolationMode.HighQualityBicubic;e.Graphics.DrawImage(b,20,20,480,480);using var pen=new Pen(Color.FromArgb(70,cyan),1);e.Graphics.DrawRectangle(pen,19,19,481,481);if(selected!=null){var r=Bounds(selected);using var sel=new Pen(cyan,2);e.Graphics.DrawRectangle(sel,20+r.X-4,20+r.Y-3,r.Width+8,r.Height+6);}}
 void DrawWidget(Graphics g,Widget w){string s=w.Text.Replace("{time}",DateTime.Now.ToString("HH:mm")).Replace("{date}",DateTime.Now.ToString("dd.MM.yyyy"));if(w.Kind=="sensor"){var key=w.SensorKey??Best(w.Hint);s=s.Replace("{value}",key!=null&&snap.TryGetValue(key,out var v)?Format(key,v):"--");}using var f=new Font("Segoe UI",w.Size,FontStyle.Bold,GraphicsUnit.Pixel);using var shadow=new SolidBrush(Color.FromArgb(130,0,0,0));using var brush=new SolidBrush(w.Color);g.DrawString(s,f,shadow,w.X+2,w.Y+2);g.DrawString(s,f,brush,w.X,w.Y);}
 Rectangle Bounds(Widget w){using var b=new Bitmap(1,1);using var g=Graphics.FromImage(b);using var f=new Font("Segoe UI",w.Size,FontStyle.Bold,GraphicsUnit.Pixel);var s=w.Text.Replace("{time}","00:00").Replace("{value}","100°C");var z=g.MeasureString(s,f);return new(w.X,w.Y,Math.Min(440,(int)z.Width+4),(int)z.Height+2);}
 void MouseDownPreview(object? s,MouseEventArgs e){int x=e.X-20,y=e.Y-20;selected=widgets.AsEnumerable().Reverse().FirstOrDefault(w=>Bounds(w).Contains(x,y));drag=selected;if(drag!=null){dragOffset=new(x-drag.X,y-drag.Y);Select(drag);}preview.Invalidate();}
 void MouseMovePreview(object? s,MouseEventArgs e){if(e.Button!=MouseButtons.Left||drag==null)return;drag.X=Math.Clamp(e.X-20-dragOffset.X,0,450);drag.Y=Math.Clamp(e.Y-20-dragOffset.Y,0,450);preview.Invalidate();}
 void Add(string kind){if(kind=="background"){ChooseBackground();return;}if(kind=="text")widgets.Add(new("text","LOVINGCOOL",38,320,30));else if(kind=="clock")widgets.Add(new("clock","{time}",120,195,64));else{var key=Best(kind);widgets.Add(new("sensor",Friendly(kind)+"  {value}",38,320,26){SensorKey=key,Hint=kind});}RefreshLayers();}
 void AddSensor(){if(sensorPicker.SelectedItem is SensorChoice c){widgets.Add(new("sensor",c.Label+"  {value}",38,320,25){SensorKey=c.Key});RefreshLayers();}}
 void RefreshSensors(){snap=sensors.Snapshot();var current=(sensorPicker.SelectedItem as SensorChoice)?.Key;sensorPicker.Items.Clear();foreach(var k in UsefulKeys(snap.Keys))sensorPicker.Items.Add(new SensorChoice(k,FriendlySensor(k)));if(sensorPicker.Items.Count>0)sensorPicker.SelectedIndex=Math.Max(0,sensorPicker.Items.Cast<SensorChoice>().ToList().FindIndex(x=>x.Key==current));}
 IEnumerable<string> UsefulKeys(IEnumerable<string> keys){var a=keys.ToList();var preferred=a.Where(k=>!k.Contains("Thread",StringComparison.OrdinalIgnoreCase)&&!k.Contains("Core #",StringComparison.OrdinalIgnoreCase)&&!k.Contains("Distance",StringComparison.OrdinalIgnoreCase)&&!k.Contains("Max",StringComparison.OrdinalIgnoreCase));return preferred.OrderBy(k=>Rank(k)).ThenBy(k=>k).Take(80);}
 int Rank(string k){if(k.Contains("CPU",StringComparison.OrdinalIgnoreCase)&&k.Contains("Temperature"))return 0;if((k.Contains("GPU",StringComparison.OrdinalIgnoreCase)||k.Contains("NVIDIA",StringComparison.OrdinalIgnoreCase)||k.Contains("AMD",StringComparison.OrdinalIgnoreCase))&&k.Contains("Temperature"))return 1;if(k.Contains("CPU",StringComparison.OrdinalIgnoreCase)&&k.Contains("Load"))return 2;if(k.Contains("GPU",StringComparison.OrdinalIgnoreCase)&&k.Contains("Load"))return 3;if(k.Contains("Memory",StringComparison.OrdinalIgnoreCase)&&k.Contains("Load"))return 4;if(k.Contains("Power"))return 5;if(k.Contains("Fan"))return 6;return 20;}
 string? Best(string? hint){if(string.IsNullOrEmpty(hint))return null;return UsefulKeys(snap.Keys).FirstOrDefault(k=>k.Contains(hint,StringComparison.OrdinalIgnoreCase));}
 string Friendly(string k)=>k switch{"Temperature"=>"TEMP","Load"=>"LOAD","Clock"=>"CLOCK","Power"=>"POWER","Fan"=>"FAN","Memory"=>"RAM","Network"=>"NET",_=>k.ToUpperInvariant()};
 string FriendlySensor(string k){var a=k.Split('•',StringSplitOptions.TrimEntries);return a.Length>=3?$"{a[0]} · {a[^1]}":k;}
 void Select(Widget w){selected=w;propText.Text=w.Text;propSize.Value=Math.Clamp(w.Size,10,110);}
 void Apply(){if(selected==null)return;selected.Text=propText.Text;selected.Size=(int)propSize.Value;RefreshLayers();preview.Invalidate();}
 void Delete(){if(selected==null)return;widgets.Remove(selected);selected=null;RefreshLayers();preview.Invalidate();}
 void RefreshLayers(){layerList.Controls.Clear();for(int i=widgets.Count-1;i>=0;i--){var w=widgets[i];var b=ButtonX("≡  "+w.Text,(_,_)=>Select(w));b.Width=280;b.Height=34;b.TextAlign=ContentAlignment.MiddleLeft;layerList.Controls.Add(b);}}
 void Preset(string n){widgets.Clear();background=null;if(n=="MINIMAL"){widgets.Add(new("clock","{time}",126,165,72));widgets.Add(new("sensor","CPU  {value}",170,285,25){Hint="CPU"});}else if(n=="CLOCK"){widgets.Add(new("clock","{time}",105,150,82));widgets.Add(new("text","{date}",158,260,24));}else if(n=="SYSTEM"){widgets.Add(new("sensor","CPU  {value}",45,70,30){SensorKey=Best("CPU"),Hint="CPU"});widgets.Add(new("sensor","GPU  {value}",45,130,30){SensorKey=Best("GPU"),Hint="GPU"});widgets.Add(new("sensor","RAM  {value}",45,190,30){SensorKey=Best("Memory"),Hint="Memory"});widgets.Add(new("clock","{time}",45,330,58));}else{widgets.Add(new("clock","{time}",130,190,66));widgets.Add(new("sensor","CPU  {value}",40,55,26){SensorKey=Best("CPU"),Hint="CPU"});widgets.Add(new("sensor","GPU  {value}",300,55,26){SensorKey=Best("GPU"),Hint="GPU"});}RefreshLayers();preview.Invalidate();}
 void ChooseBackground(){using var d=new OpenFileDialog{Filter="Изображения|*.png;*.jpg;*.jpeg;*.bmp;*.webp"};if(d.ShowDialog()==DialogResult.OK){using var im=Image.FromFile(d.FileName);background=Fit(new Bitmap(im));preview.Invalidate();}}
 static Bitmap Fit(Bitmap src){var d=new Bitmap(480,480);using var g=Graphics.FromImage(d);g.InterpolationMode=InterpolationMode.HighQualityBicubic;float z=Math.Max(480f/src.Width,480f/src.Height);int w=(int)(src.Width*z),h=(int)(src.Height*z);g.DrawImage(src,(480-w)/2,(480-h)/2,w,h);return d;}
 string Format(string k,float v){if(k.Contains("Temperature"))return $"{v:0}°C";if(k.Contains("Load"))return $"{v:0}%";if(k.Contains("Clock"))return $"{v:0} MHz";if(k.Contains("Power"))return $"{v:0.0} W";if(k.Contains("Fan"))return $"{v:0} RPM";if(k.Contains("Data"))return $"{v:0.0} GB";return $"{v:0.0}";}
 void SaveScene(){try{var path=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"LOVINGCOOL Studio");Directory.CreateDirectory(path);File.WriteAllText(Path.Combine(path,"scene.json"),JsonSerializer.Serialize(widgets));}catch{}}
 void LoadScene(){try{var f=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"LOVINGCOOL Studio","scene.json");if(File.Exists(f)){var x=JsonSerializer.Deserialize<List<Widget>>(File.ReadAllText(f));if(x!=null)widgets.AddRange(x);}}catch{}if(widgets.Count==0)Preset("SYSTEM");else RefreshLayers();}
 void ToggleStartup(){try{using var k=Registry.CurrentUser.OpenSubKey(@"Software\Microsoft\Windows\CurrentVersion\Run",true)!;const string n="LOVINGCOOL Studio";if(k.GetValue(n)==null){k.SetValue(n,$"\"{Application.ExecutablePath}\"");MessageBox.Show("Автозапуск включён.");}else{k.DeleteValue(n,false);MessageBox.Show("Автозапуск выключен.");}}catch(Exception ex){MessageBox.Show(ex.Message);}}
 void SetupTray(){tray.Text="LOVINGCOOL Studio";tray.Icon=Icon??SystemIcons.Application;tray.Visible=true;var m=new ContextMenuStrip();m.Items.Add("Открыть",null,(_,_)=>{Show();WindowState=FormWindowState.Maximized;});m.Items.Add("Выход",null,(_,_)=>Application.Exit());tray.ContextMenuStrip=m;tray.DoubleClick+=(_,_)=>Show();}
 public sealed class Widget{public string Kind{get;set;}="text";public string Text{get;set;}="";public int X{get;set;}public int Y{get;set;}public int Size{get;set;}=28;public string? SensorKey{get;set;}public string? Hint{get;set;}[System.Text.Json.Serialization.JsonIgnore]public Color Color{get;set;}=Color.White;public Widget(){}public Widget(string k,string t,int x,int y,int s){Kind=k;Text=t;X=x;Y=y;Size=s;}}
 sealed record SensorChoice(string Key,string Label){public override string ToString()=>Label;}
 sealed class PreviewCanvas:Panel{public PreviewCanvas(){DoubleBuffered=true;ResizeRedraw=true;}}
}